import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

// Providers
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { ModalProvider } from "@/providers/modal-provider";

export const metadata: Metadata = {
  title: "Nomad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={`${GeistSans.className} antialiased`}>
          <ConvexClientProvider>
            <ModalProvider>{children}</ModalProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
